name: min node version
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Cypress Docker image with minimum Node version
    # we promise to support in this repo
    # https://github.com/cypress-io/cypress-docker-images/tree/master/base
    container: cypress/base:12.0.0-libgbm
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # let's find what the environment provides
          build: npx cypress info
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/07-ci/*'
